### ISSUE TITLE
noting happens after installation

### ISSUE THREAD

**Issue by assafShapira** [logicmonitor/k8s-argus#76]
-   **Argus Version:**
argus-0.2.0
-   **Kubernetes Version:**
1.10

after installing Argus
the Argus and the collector pods are up, not errors on their logs, but nothing happens...

this is the only logs I'm getting
time="2018-06-13T11:34:46Z" level=info msg="Waiting for gRPC"
time="2018-06-13T11:34:46Z" level=info msg="State of gRPC is \"READY\""

tried to set the debug flag to true. still the same log messages

thanks ahead,
assaf

**Comment by andrewrynhard** [comment]
@assafShapira It isn't quite documented yet, but now that the controller is running, you will need to create the following with `kubectl`:

```yaml
apiVersion: logicmonitor.com/v1alpha1
  kind: CollectorSet
  metadata:
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    policy:
      distributionStrategy: RoundRobin
      orchestrator: Kubernetes
    replicas: 2
    size: medium
```
